settings:
  # Currency item settings
  currency:
    material: AMETHYST_SHARD
    custom_model_data: 1001
    enchanted:
      material: AMETHYST_SHARD
      custom_model_data: 1002
      conversion_rate: 10  # Regular shards needed for 1 enchanted shard

  # Message settings
  messages:
    enabled: true
    prefix: "ยง8[ยงbShardsยง8]"
    shard_gain: "%prefix% ยงa+%amount% shards!"
    insufficient_shards: "%prefix% ยงcYou don't have enough shards!"
    purchase_success: "%prefix% ยงaYou purchased %item%!"
    error_occurred: "%prefix% ยงcAn error occurred while processing your purchase."
    balance: "%prefix% ยงaYou have %amount% shards!"
    give_shards_sender: "%prefix% ยงaGave %amount% shards to %player%"
    give_shards_receiver: "%prefix% ยงaYou received %amount% shards!"
    player_not_found: "%prefix% ยงcPlayer not found!"
    no_permission: "%prefix% ยงcYou don't have permission to use this command!"
    invalid_amount: "%prefix% ยงcInvalid amount!"
    cannot_drop_armor: "%prefix% ยงcYou cannot drop special armor pieces!"
    cannot_drop_pickaxe: "%prefix% ยงcYou cannot drop special pickaxes!"
    enchanted_shard_purchase: "%prefix% ยงaYou converted %regular% regular shards into %enchanted% enchanted shards!"

  # GUI settings
  gui:
    title: "Equipment Shop - Page %page%"
    size: 54  # 6 rows of 9 slots
    # Fill empty slots with this item (optional)
    filler:
      material: GRAY_STAINED_GLASS_PANE
      name: " "
    navigation:
      previous_page:
        slot: 45
        material: ARROW
        name: "ยงeโ Previous Page"
      next_page:
        slot: 53
        material: ARROW
        name: "ยงeโ Next Page"
      info:
        slot: 49
        material: BOOK
        name: "ยงePage %page%/%total%"
    enchanted_shard:
      slot: 4
      material: AMETHYST_SHARD
      custom_model_data: 1002
      name: "ยงdโจ Enchanted Shard"
      lore:
        - "ยง7A mystical shard infused with"
        - "ยง7magical properties."
        - ""
        - "ยง7Cost: ยงe10 regular shards"
        - ""
        - "ยงdClick to convert regular shards"
        - "ยงdinto enchanted shards!"

  # Blocks that drop shards when broken
  shard_blocks:
    DIAMOND_ORE:
      amount: 5
      commands:
        - "give %player% minecraft:diamond 1"
        - "effect give %player% minecraft:haste 30 1"
    EMERALD_ORE:
      amount: 4
      commands:
        - "give %player% minecraft:emerald 1"
        - "effect give %player% minecraft:luck 30 1"
    GOLD_ORE:
      amount: 3
      commands:
        - "give %player% minecraft:raw_gold 1"
    IRON_ORE:
      amount: 2
      commands:
        - "give %player% minecraft:raw_iron 1"
    COAL_ORE:
      amount: 1
      commands:
        - "give %player% minecraft:coal 1"

armor_sets:
  # Basic Miner Set
  MINER:
    name: "Miner's Armor"
    multiplier: 1.2
    rolls: 1
    page: 1
    slots:
      helmet: 10
      chestplate: 19
      leggings: 28
      boots: 37
    cost:
      helmet: 100
      chestplate: 150
      leggings: 125
      boots: 75
    # GUI display settings for each piece
    gui:
      helmet:
        material: DIAMOND_HELMET
        display_name: "ยง6โ Miner's Helmet"
        custom_model_data: 1001
        lore:
          - "ยง7A sturdy helmet for mining"
          - "ยง7Provides night vision underground"
          - ""
          - "ยง6Set Bonus: ยงe+20% Shard Drop Rate"
      chestplate:
        material: DIAMOND_CHESTPLATE
        display_name: "ยง6โ Miner's Chestplate"
        custom_model_data: 1002
        lore:
          - "ยง7Reinforced for cave exploration"
          - "ยง7Extra protection against falling rocks"
          - ""
          - "ยง6Set Bonus: ยงe+20% Shard Drop Rate"
      leggings:
        material: DIAMOND_LEGGINGS
        display_name: "ยง6โ Miner's Leggings"
        custom_model_data: 1003
        lore:
          - "ยง7Flexible yet durable"
          - "ยง7Perfect for long mining sessions"
          - ""
          - "ยง6Set Bonus: ยงe+20% Shard Drop Rate"
      boots:
        material: DIAMOND_BOOTS
        display_name: "ยง6โ Miner's Boots"
        custom_model_data: 1004
        lore:
          - "ยง7Steel-toed boots"
          - "ยง7Prevents stubbed toes on rocks"
          - ""
          - "ยง6Set Bonus: ยงe+20% Shard Drop Rate"
    # Actual armor piece settings
    armor:
      helmet:
        material: DIAMOND_HELMET
        display_name: "ยง6โ Miner's Helmet"
        custom_model_data: 1001
        lore:
          - "ยง7A sturdy helmet for mining"
          - "ยง7Provides night vision underground"
      chestplate:
        material: DIAMOND_CHESTPLATE
        display_name: "ยง6โ Miner's Chestplate"
        custom_model_data: 1002
        lore:
          - "ยง7Reinforced for cave exploration"
          - "ยง7Extra protection against falling rocks"
      leggings:
        material: DIAMOND_LEGGINGS
        display_name: "ยง6โ Miner's Leggings"
        custom_model_data: 1003
        lore:
          - "ยง7Flexible yet durable"
          - "ยง7Perfect for long mining sessions"
      boots:
        material: DIAMOND_BOOTS
        display_name: "ยง6โ Miner's Boots"
        custom_model_data: 1004
        lore:
          - "ยง7Steel-toed boots"
          - "ยง7Prevents stubbed toes on rocks"

  # Forest Guardian Set
  FOREST_GUARDIAN:
    name: "Forest Guardian's Armor"
    multiplier: 1.5
    rolls: 2
    page: 1
    slots:
      helmet: 11
      chestplate: 20
      leggings: 29
      boots: 38
    cost:
      helmet: 200
      chestplate: 300
      leggings: 250
      boots: 150
    # GUI display settings
    gui:
      helmet:
        material: LEATHER_HELMET
        display_name: "ยง2๐ณ Forest Guardian's Hood"
        custom_model_data: 2001
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Blends with the forest canopy"
          - "ยง7Enchanted with nature's blessing"
          - ""
          - "ยง6Set Bonus: ยงe+50% Shard Drop Rate"
      chestplate:
        material: LEATHER_CHESTPLATE
        display_name: "ยง2๐ณ Forest Guardian's Tunic"
        custom_model_data: 2002
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Woven from enchanted leaves"
          - "ยง7Provides camouflage in forests"
          - ""
          - "ยง6Set Bonus: ยงe+50% Shard Drop Rate"
      leggings:
        material: LEATHER_LEGGINGS
        display_name: "ยง2๐ณ Forest Guardian's Leggings"
        custom_model_data: 2003
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Light as a feather"
          - "ยง7Perfect for forest traversal"
          - ""
          - "ยง6Set Bonus: ยงe+50% Shard Drop Rate"
      boots:
        material: LEATHER_BOOTS
        display_name: "ยง2๐ณ Forest Guardian's Boots"
        custom_model_data: 2004
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Silent steps through the woods"
          - "ยง7Leaves no footprints"
          - ""
          - "ยง6Set Bonus: ยงe+50% Shard Drop Rate"
    # Actual armor piece settings
    armor:
      helmet:
        material: LEATHER_HELMET
        display_name: "ยง2๐ณ Forest Guardian's Hood"
        custom_model_data: 2001
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Blends with the forest canopy"
          - "ยง7Enchanted with nature's blessing"
      chestplate:
        material: LEATHER_CHESTPLATE
        display_name: "ยง2๐ณ Forest Guardian's Tunic"
        custom_model_data: 2002
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Woven from enchanted leaves"
          - "ยง7Provides camouflage in forests"
      leggings:
        material: LEATHER_LEGGINGS
        display_name: "ยง2๐ณ Forest Guardian's Leggings"
        custom_model_data: 2003
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Light as a feather"
          - "ยง7Perfect for forest traversal"
      boots:
        material: LEATHER_BOOTS
        display_name: "ยง2๐ณ Forest Guardian's Boots"
        custom_model_data: 2004
        color:
          red: 34
          green: 139
          blue: 34
        lore:
          - "ยง7Silent steps through the woods"
          - "ยง7Leaves no footprints"

  # Nether King Set
  NETHER_KING:
    name: "Nether King's Armor"
    multiplier: 2.0
    rolls: 3
    page: 1
    slots:
      helmet: 12
      chestplate: 21
      leggings: 30
      boots: 39
    cost:
      helmet: 400
      chestplate: 600
      leggings: 500
      boots: 300
    # GUI display settings
    gui:
      helmet:
        material: NETHERITE_HELMET
        display_name: "ยง4๐ Nether King's Crown"
        custom_model_data: 3001
        lore:
          - "ยง7Forged in ancient fire"
          - "ยง7Commands respect from Piglins"
          - "ยง4ยงlInfused with hellfire"
          - ""
          - "ยง6Set Bonus: ยงe+100% Shard Drop Rate"
      chestplate:
        material: NETHERITE_CHESTPLATE
        display_name: "ยง4๐ Nether King's Platemail"
        custom_model_data: 3002
        lore:
          - "ยง7Tempered in lava streams"
          - "ยง7Radiates intense heat"
          - "ยง4ยงlBurns attackers"
          - ""
          - "ยง6Set Bonus: ยงe+100% Shard Drop Rate"
      leggings:
        material: NETHERITE_LEGGINGS
        display_name: "ยง4๐ Nether King's Greaves"
        custom_model_data: 3003
        lore:
          - "ยง7Crafted from pure netherite"
          - "ยง7Allows walking on lava"
          - "ยง4ยงlInfernal protection"
          - ""
          - "ยง6Set Bonus: ยงe+100% Shard Drop Rate"
      boots:
        material: NETHERITE_BOOTS
        display_name: "ยง4๐ Nether King's Sabatons"
        custom_model_data: 3004
        lore:
          - "ยง7Blessed by the Nether"
          - "ยง7Leaves burning footprints"
          - "ยง4ยงlUntouchable by fire"
          - ""
          - "ยง6Set Bonus: ยงe+100% Shard Drop Rate"
    # Actual armor piece settings
    armor:
      helmet:
        material: NETHERITE_HELMET
        display_name: "ยง4๐ Nether King's Crown"
        custom_model_data: 3001
        lore:
          - "ยง7Forged in ancient fire"
          - "ยง7Commands respect from Piglins"
          - "ยง4ยงlInfused with hellfire"
      chestplate:
        material: NETHERITE_CHESTPLATE
        display_name: "ยง4๐ Nether King's Platemail"
        custom_model_data: 3002
        lore:
          - "ยง7Tempered in lava streams"
          - "ยง7Radiates intense heat"
          - "ยง4ยงlBurns attackers"
      leggings:
        material: NETHERITE_LEGGINGS
        display_name: "ยง4๐ Nether King's Greaves"
        custom_model_data: 3003
        lore:
          - "ยง7Crafted from pure netherite"
          - "ยง7Allows walking on lava"
          - "ยง4ยงlInfernal protection"
      boots:
        material: NETHERITE_BOOTS
        display_name: "ยง4๐ Nether King's Sabatons"
        custom_model_data: 3004
        lore:
          - "ยง7Blessed by the Nether"
          - "ยง7Leaves burning footprints"
          - "ยง4ยงlUntouchable by fire"

  # Void Armor Set
  VOID:
    name: "Void Armor"
    multiplier: 3.0
    rolls: 4
    page: 1
    slots:
      helmet: 13
      chestplate: 22
      leggings: 31
      boots: 40
    cost_enchanted:  # Using enchanted shards instead of regular shards
      helmet: 5
      chestplate: 8
      leggings: 7
      boots: 4
    # GUI display settings
    gui:
      helmet:
        material: NETHERITE_HELMET
        display_name: "ยง5โซ Void Walker's Crown"
        custom_model_data: 5001
        lore:
          - "ยง7Forged in the depths of the void"
          - "ยง7Grants vision in absolute darkness"
          - "ยง5ยงlVoid-touched"
          - ""
          - "ยงdยงlCost: ยง5โจ 5 Enchanted Shards"
          - ""
          - "ยง6Set Bonus: ยงe+200% Shard Drop Rate"
      chestplate:
        material: NETHERITE_CHESTPLATE
        display_name: "ยง5โซ Void Walker's Embrace"
        custom_model_data: 5002
        lore:
          - "ยง7Pulsing with void energy"
          - "ยง7Protects against the unknown"
          - "ยง5ยงlVoid-infused"
          - ""
          - "ยงdยงlCost: ยง5โจ 8 Enchanted Shards"
          - ""
          - "ยง6Set Bonus: ยงe+200% Shard Drop Rate"
      leggings:
        material: NETHERITE_LEGGINGS
        display_name: "ยง5โซ Void Walker's Stride"
        custom_model_data: 5003
        lore:
          - "ยง7Woven from pure darkness"
          - "ยง7Allows walking through shadows"
          - "ยง5ยงlVoid-blessed"
          - ""
          - "ยงdยงlCost: ยง5โจ 7 Enchanted Shards"
          - ""
          - "ยง6Set Bonus: ยงe+200% Shard Drop Rate"
      boots:
        material: NETHERITE_BOOTS
        display_name: "ยง5โซ Void Walker's Steps"
        custom_model_data: 5004
        lore:
          - "ยง7Touched by the void itself"
          - "ยง7Leaves trails of darkness"
          - "ยง5ยงlVoid-bound"
          - ""
          - "ยงdยงlCost: ยง5โจ 4 Enchanted Shards"
          - ""
          - "ยง6Set Bonus: ยงe+200% Shard Drop Rate"
    # Actual armor piece settings
    armor:
      helmet:
        material: NETHERITE_HELMET
        display_name: "ยง5โซ Void Walker's Crown"
        custom_model_data: 5001
        lore:
          - "ยง7Forged in the depths of the void"
          - "ยง7Grants vision in absolute darkness"
          - "ยง5ยงlVoid-touched"
      chestplate:
        material: NETHERITE_CHESTPLATE
        display_name: "ยง5โซ Void Walker's Embrace"
        custom_model_data: 5002
        lore:
          - "ยง7Pulsing with void energy"
          - "ยง7Protects against the unknown"
          - "ยง5ยงlVoid-infused"
      leggings:
        material: NETHERITE_LEGGINGS
        display_name: "ยง5โซ Void Walker's Stride"
        custom_model_data: 5003
        lore:
          - "ยง7Woven from pure darkness"
          - "ยง7Allows walking through shadows"
          - "ยง5ยงlVoid-blessed"
      boots:
        material: NETHERITE_BOOTS
        display_name: "ยง5โซ Void Walker's Steps"
        custom_model_data: 5004
        lore:
          - "ยง7Touched by the void itself"
          - "ยง7Leaves trails of darkness"
          - "ยง5ยงlVoid-bound"

pickaxes:
  # Basic Miner's Pickaxe
  BASIC_MINER:
    name: "Basic Miner's Pickaxe"
    multiplier: 1.2
    rolls: 1
    page: 2
    slot: 10
    cost: 200
    gui:
      material: IRON_PICKAXE
      display_name: "ยง7โ Basic Miner's Pickaxe"
      custom_model_data: 4001
      lore:
        - "ยง7A simple but reliable tool"
        - "ยง7Perfect for beginners"
        - ""
        - "ยง6Bonus: ยงe+20% Shard Drop Rate"
        - "ยง6Extra Roll: ยงe1x"
    item:
      material: IRON_PICKAXE
      display_name: "ยง7โ Basic Miner's Pickaxe"
      custom_model_data: 4001
      lore:
        - "ยง7A simple but reliable tool"
        - "ยง7Perfect for beginners"

  # Gem Hunter's Pickaxe
  GEM_HUNTER:
    name: "Gem Hunter's Pickaxe"
    multiplier: 1.5
    rolls: 2
    page: 2
    slot: 11
    cost: 400
    gui:
      material: DIAMOND_PICKAXE
      display_name: "ยงb๐ Gem Hunter's Pickaxe"
      custom_model_data: 4002
      lore:
        - "ยง7Specially designed for gem mining"
        - "ยง7Increased luck with precious stones"
        - ""
        - "ยง6Bonus: ยงe+50% Shard Drop Rate"
        - "ยง6Extra Rolls: ยงe2x"
    item:
      material: DIAMOND_PICKAXE
      display_name: "ยงb๐ Gem Hunter's Pickaxe"
      custom_model_data: 4002
      lore:
        - "ยง7Specially designed for gem mining"
        - "ยง7Increased luck with precious stones"

  # Hellforge Pickaxe
  HELLFORGE:
    name: "Hellforge Pickaxe"
    multiplier: 2.0
    rolls: 3
    page: 2
    slot: 12
    cost: 800
    gui:
      material: NETHERITE_PICKAXE
      display_name: "ยง4๐ฅ Hellforge Pickaxe"
      custom_model_data: 4003
      lore:
        - "ยง7Forged in the depths of the Nether"
        - "ยง7Melts through stone like butter"
        - "ยง4ยงlInfused with hellfire"
        - ""
        - "ยง6Bonus: ยงe+100% Shard Drop Rate"
        - "ยง6Extra Rolls: ยงe3x"
    item:
      material: NETHERITE_PICKAXE
      display_name: "ยง4๐ฅ Hellforge Pickaxe"
      custom_model_data: 4003
      lore:
        - "ยง7Forged in the depths of the Nether"
        - "ยง7Melts through stone like butter"
        - "ยง4ยงlInfused with hellfire"